<?php

namespace App\ElektronicznyNadawca;

class serwisPrzesylkaProceduralnaType
{
    const __default = 'PROCEDURALNA_STANDARD_DWA_STOPNIE';
    const PROCEDURALNA_STANDARD_DWA_STOPNIE = 'PROCEDURALNA_STANDARD_DWA_STOPNIE';
    const PROCEDURALNA_VIP_DWA_STOPNIE = 'PROCEDURALNA_VIP_DWA_STOPNIE';
    const PROCEDURALNA_STANDARD_TRZY_STOPNIE = 'PROCEDURALNA_STANDARD_TRZY_STOPNIE';
    const PROCEDURALNA_VIP_TRZY_STOPNIE = 'PROCEDURALNA_VIP_TRZY_STOPNIE';


}
